version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    volumes:
      - ./auth-service:/app
    environment:
      - NODE_ENV=development

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    volumes:
      - ./product-service:/app
    environment:
      - NODE_ENV=development

  cart-service:
    build: ./cart-service
    ports:
      - "3003:3003"
    volumes:
      - ./cart-service:/app
    environment:
      - NODE_ENV=development

  order-service:
    build: ./order-service
    ports:
      - "3004:3004"
    volumes:
      - ./order-service:/app
    environment:
      - NODE_ENV=development

  notification-service:
    build: ./notification-service
    ports:
      - "3005:3005"
    volumes:
      - ./notification-service:/app
    environment:
      - NODE_ENV=development

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./api-gateway:/app
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3000
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - CART_SERVICE_URL=http://cart-service:3003
      - ORDER_SERVICE_URL=http://order-service:3004
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
      - JWT_SECRET=your-secret 